rose_pine_base: \#191724
rose_pine_surface: \#1f1d2e
rose_pine_overlay: \#26233a
rose_pine_muted: \#6e6a86
rose_pine_subtle: \#908caa
rose_pine_text: \#e0def4
rose_pine_love: \#eb6f92
rose_pine_gold: \#f6c177
rose_pine_rose: \#ebbcba
rose_pine_pine: \#31748f
rose_pine_foam: \#9ccfd8
rose_pine_iris: \#c4a7e7
rose_pine_highlightLow: \#21202e
rose_pine_highlightMed: \#403d52
rose_pine_highlightHigh: \#524f67

rose_pine_moon_base: \#232136
rose_pine_moon_surface: \#2a273f
rose_pine_moon_overlay: \#393552
rose_pine_moon_muted: \#6e6a86
rose_pine_moon_subtle: \#908caa
rose_pine_moon_text: \#e0def4
rose_pine_moon_love: \#eb6f92
rose_pine_moon_gold: \#f6c177
rose_pine_moon_rose: \#ea9a97
rose_pine_moon_pine: \#3e8fb0
rose_pine_moon_foam: \#9ccfd8
rose_pine_moon_iris: \#c4a7e7
rose_pine_moon_highlightLow: \#2a283e
rose_pine_moon_hlghlightMed: \#44415a
rose_pine_moon_hlghlightHigh: \#56526e

rose_pine_dawm_base: \#faf4ed
rose_pine_dawn_surface: \#fffaf3
rose_pine_dawn_overlay: \#f2e9e1
rose_pine_dawn_muted: \#9893a5
rose_pine_dawn_subtle: \#797593
rose_pine_dawn_text: \#575279
rose_pine_dawn_love: \#b4637a
rose_pine_dawn_gold: \#ea9d34
rose_pine_dawn_rose: \#d7827e
rose_pine_dawn_pine: \#286983
rose_pine_dawn_foam: \#56949f
rose_pine_dawn_iris: \#907aa9
rose_pine_dawn_highlightLow: \#f4ede8
rose_pine_dawn_hlghlightMed: \#dfdad9
rose_pine_dawn_hlghlightHigh: \#cecacd

