- tags: fontconfig
  block:

    - name: fontconfig - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - fontconfig    # Library for configuring and customizing font access


    - name: Get fonts
      # I cannot include propietary fonts in a public repo, all fonts should 
      # be stored in a private repository
      block:
        - name: Clone the private `arch-fonts` repository


    - name: Create config files
      block:
      - name: alacritty - Create directories
        ansible.builtin.file:
          path: "{{ home }}/.config/alacritty"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '700'
          state: directory

      - name: alacritty - Create links
        ansible.builtin.file:
          src: "{{ repo_dir }}/tasks/config/alacritty/files/{{ item.name }}"
          path: "{{ home }}/.config/alacritty/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '600'
          state: "link"
        loop:
          - { name: "alacritty.yml" }

      - name: alacritty - Process templates
        tags: theme
        ansible.builtin.template:
          src: "files/{{ item.name }}"
          dest: "{{ home }}/.config/alacritty/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '600'
        loop:
          - { name: "theme.yml" }

