import = ["/home/mabq/.config/alacritty/theme.toml"]

[env]
# (this is required in order to correctly display the colors in tmux)
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "monospace-double"
style = "Bold"

[font.bold_italic]
family = "monospace-double"
style = "Bold Italic"

[font.italic]
family = "monospace-double"
style = "Italic"

[font.normal]
family = "monospace-double"
style = "Regular"

[scrolling]
multiplier = 1
