# Configuration docs: https://alacritty.org/config-alacritty.html

[general]
import = ["~/.config/alacritty/themes/tokyonight_night.toml"]
live_config_reload = true

[scrolling]
multiplier = 1

[font]
size = 10

normal = { family = "Berkeley Mono Variable", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Oblique" }
bold_italic = { style = "Bold Oblique" }

# normal = { family = "Iosevka Fixed", style = "Medium" }
# bold = { style = "Bold" }
# italic = { style = "Italic" }
# bold_italic = { style = "Bold Italic" }

# normal = { family = "Cartograph CF ", style = "Regular" }
# bold = { style = "Bold" }
# italic = { style = "Italic" }
# bold_italic = { style = "Bold Italic" }

offset = { x = 0, y = 1  } # increase line height
# glyph_offset = { x = 0, y = 1  } # center the glyph

# [colors]
# draw_bold_text_with_bright_colors = true

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[env]
# (this is required in order to correctly display the colors in tmux)
TERM = "xterm-256color"
