# ------------------------------------------------------------------------------
#
#               _____                    _       _         _
#              |_   _|__ _ __ ___  _ __ | | __ _| |_ ___  | |
#                | |/ _ \ '_ ` _ \| '_ \| |/ _` | __/ _ \ | |
#                | |  __/ | | | | | |_) | | (_| | ||  __/ |_|
#                |_|\___|_| |_| |_| .__/|_|\__,_|\__\___| (_)
#                                 |_|
#
# ------------------------------------------------------------------------------

# pick your theme and re-run ansible
import = [{{ repo_dir }}config/alacritty/files/themes/catppuccin-mocha.toml]

[env]
# (this is required in order to correctly display the colors in tmux)
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "monospace-double"
style = "Bold"

[font.bold_italic]
family = "monospace-double"
style = "Bold Italic"

[font.italic]
family = "monospace-double"
style = "Italic"

[font.normal]
family = "monospace-double"
style = "Regular"

[scrolling]
multiplier = 1
