- tags: kanata
  block:
    - name: Install
      block:
        - name: kanata - Check if kanata is already installed
          ansible.builtin.command: "which kanata"
          register: which_kanata
          ignore_errors: true

        - name: kanata - Install kanata
          when: which_kanata.rc != 0
          # Bring the customizability of a QMK board to any keyboard near you
          ansible.builtin.shell: "paru -S --skipreview kanata"

    - name: kanata - Link the whole directory
      # link the whole directory, there is nothing sensible here
      ansible.builtin.file:
        src: "{{ repo_dir }}/config/kanata/files"
        path: "{{ home }}/.config/kanata"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0700"
        state: "link"
