- tags: kmonad
  block:

    - name: Install required packages
      block:

      - name: kmonad - Install package from AUR
        tags: aur
        block:
          - name: kmonad - Check if kmonad is already installed
            ansible.builtin.command: "which kmonad"
            register: which_kmonad
            ignore_errors: true

          - name: kmonad - Install kmonad
            when: which_kmonad.rc != 0
            # An advanced keyboard manager - static binary version
            ansible.builtin.shell: 'paru -S --skipreview kmonad-bin'

      - name: kmonad - Install evtest
        become: true
        community.general.pacman:
          state: latest
          name:
            - evtest    # Input device event monitor and query tool (required to identify the keyboard address)


    - name: Create config files
      block:
      - name: kmonad - Create directories
        ansible.builtin.file:
          path: "{{ home }}/.config/kmonad"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: 0700
          state: directory

      - name: kmonad - Create links
        ansible.builtin.file:
          src: "{{ repo_dir }}/tasks/config/kmonad/files/{{ item.name }}"
          path: "{{ home }}/.config/kmonad/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '700'
          state: "link"
        loop:
          - { name: "mxkeys.kbd" }
          - { name: "apple.kbd" }


    - name: Get uinput permissions
      # https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions
      block:
        - name: kmonad - Ensure the `uinput` group exists
          become: true
          ansible.builtin.group:
            name: uinput
            state: present
 
        - name: kmonad - Add your user to the `input` and the `uinput` group
          become: true
          ansible.builtin.user:
            append: true
            groups: input,uinput
            name: "{{ user }}"

        - name: kmonad - Ensure the `uinput` device file has the right permissions
          become: true
          ansible.builtin.copy:
            content: 'KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"'
            dest: /etc/udev/rules.d/99-kmonad.rules
          register: rule

        - name: kmonad - Ensure the `uinput` drivers are loaded
          become: true
          ansible.builtin.command: modprobe uinput
          when: rule.changed


    # - name: Load the `uinput` kernel module
    #   # https://github.com/kmonad/kmonad/blob/cec7d4ac3644c96737da23124e473e13ace5156c/keymap/tutorial.kbd#L111
    #   block:
    #     - name: kmonad - Check loaded kernel modules
    #       ansible.builtin.command: 'lsmod'
    #       register: loaded_modules
    #
    #     - name: kmonad - Load `uinput` drivers (if necessary)
    #       ansible.builtin.command: modprobe uinput
    #       when: "'uinput' not in loaded_modules.stdout_lines"
