- tags: brave
  block:

    - name: Install Brave
      # Once installed, AUR packages won't be reinstalled, update them manually with `paru`
      tags: aur
      block:
        - name: no-config - Check if Brave is already installed
          ansible.builtin.command: "which brave"
          register: which_brave
          ignore_errors: true

        - name: no-config - Install Brave
          when: which_brave.rc != 0
          # Web browser that blocks ads and trackers by default (binary release)
          ansible.builtin.shell: 'paru -S --skipreview brave-bin'

      # No need to link the script, its only called with a shortcut.
