# --- Pre-tasks

- hosts: all
  become: true
  tags: always
  pre_tasks:
  - name: Exit if not running Archlinux
    ansible.builtin.fail:
      msg: This host is not running Archlinux
    when: ansible_distribution != "Archlinux"
  # - name: Synchronize and update all packages
  #   community.general.pacman:
  #     update_cache: true
  #     upgrade: true
  - name: check processor
    ansible.builtin.debug:
      msg: "{{ ansible_processor }}"
  - name: intel
    ansible.builtin.debug:
      msg: "Is intel"
    when: "Intel in {{ item }}"
    loop: "{{ ansible_processor }}"


# --- Roles

# - hosts: all
#   tags: base
#   become: true
#   roles:
#     - base
#
# - hosts: workstation
#   tags: workstation
#   become: true
#   roles:
#     - workstation

# - hosts: server
#   tags: server
#   become: true
#   roles:
#     - workstation

