- hosts: localhost
  tasks:
    - tags: always
      block:
        - import_tasks: pre/exit_if_not_arch.yml
        - import_tasks: pre/update_all_packages.yml
        - import_tasks: pre/load_theme_variables.yml
        - import_tasks: pre/change_remote_url_protocol.yml
    
    - tags: user
      block:
        - import_tasks: user/create_user.yml
        


    # no-config ---
    -

    # config ---
    -

  
