- hosts: localhost
  tasks:
    - import_tasks: tasks/pre_tasks.yml

    - import_tasks: tasks/system.yml

    - import_tasks: tasks/pacman.yml
    - import_tasks: tasks/paru.yml

    - import_tasks: tasks/no_config.yml  # must go after paru

    - import_tasks: tasks/config/alacritty/main.yml

    - import_tasks: tasks/config/git/main.yml

    - import_tasks: tasks/config/hypr/main.yml
    - import_tasks: tasks/config/hypr_dunst/main.yml
    - import_tasks: tasks/config/hypr_swaylock/main.yml
    - import_tasks: tasks/config/hypr_tofi/main.yml
    - import_tasks: tasks/config/hypr_waybar/main.yml

    - import_tasks: tasks/config/kmonad/main.yml

    - import_tasks: tasks/config/logiops/main.yml

    - import_tasks: tasks/config/ncspot/main.yml

    - import_tasks: tasks/config/swappy/main.yml

    - import_tasks: tasks/config/zsh/main.yml

    - import_tasks: tasks/config/ssh/main.yml

    - import_tasks: tasks/config/fontconfig/main.yml  # must go after ssh (clone a private repo)

    - import_tasks: tasks/config/wallpapers/main.yml


    # no-config ---
    -

    # config ---
    -
  
