# Source files

source-file $HOME/.config/tmux/source/options.conf
source-file $HOME/.config/tmux/source/bindings.conf
source-file $HOME/.config/tmux/source/bar-layout.conf
source-file $HOME/.config/tmux/source/themes/tokyonight_night.conf
