- name: Pacman setup
  tags: pacman
  block:

    - name: Configure pacman (enable colored output, verbose lists and parallel downloads)
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/pacman.conf
        regexp: '{{ item.regex }}'
        line: '{{ item.line }}'
      loop:
        - { regex: "^#Color", line: "Color" }
        - { regex: "^#VerbosePkgLists", line: "VerbosePkgLists" }
        - { regex: "^#ParallelDownloads", line: "ParallelDownloads = 10" }
        # - { regex: "^#IgnorePkg", line: "IgnorePkg   = ansible linux linux-headers linux-lts linux-lts-headers" }

    - name: Install `pacman-contrib`
      # Contributed scripts and tools for pacman systems (provides the `pactree` command)
      become: true
      community.general.pacman:
        state: latest
        name: pacman-contrib      

