- tags: system
  block:

    - name: Clock setup
      block:
        - name: Clock setup - Start and enable `systemd-timesyncd`
          ansible.builtin.service:
            name: systemd-timesyncd
            enabled: true
            state: started

        - name: Clock setup - Set time zone
          community.general.timezone:
            name: "{{ timezone }}"
            # Whether the hardware clock is in UTC or in local timezone.
            hwclock: "local"


    - name: Locale setup
      block:
        - name: Locale setup - Add locales
          community.general.locale_gen:
            name: "{{ item }}"
          loop:
            - en_US.UTF-8
            - es_EC.UTF-8
          register: locale_gen

        - name: Locale setup - Set `en_US` as default locale
          ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8
          when: locale_gen.changed


    - name: Microcode
      block:
        - name: Microcode - Install `intel-ucode`
          ansible.builtin.package:
            name: intel-ucode
            state: latest
          when: is_intel

        - name: Microcode - Install `amd-ucode`
          ansible.builtin.package:
            name: amd-ucode
            state: latest
          when: not is_intel

