- tags: nvim
  block:
    - name: nvim - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          # Neovim and external tools required by Neovim:
          - base-devel # Basic tools to build Arch Linux packages (a C compiler for nvim-treesitter)
          - neovim # Fork of Vim aiming to improve user experience, plugins, and GUIs
          - git # The fast distributed version control system
          - lazygit # Simple terminal UI for git commands (optional)
          - gitui # Blazing fast terminal-ui for git written in Rust
          - ripgrep # A search tool that combines the usability of ag with the raw speed of grep (required for telescope)
          - fd # Simple, fast and user-friendly alternative to find (required for telescope)
          - python-debugpy # An implementation of the Debug Adapter Protocol for Python
          #
          # In case you ever build Neovim from source:
          # https://github.com/neovim/neovim/blob/master/BUILD.md#arch-linux
          - base-devel # Basic tools to build Arch Linux packages
          - cmake # A cross-platform open-source make system
          - unzip # For extracting and viewing files in .zip archives
          - ninja # Small build system with a focus on speed
          - curl # Command line tool and library for transferring data with URLs

    - name: nvim - Link config files
      # link entire config directories, there is nothing sensible here
      # which version is used is determined by a zsh alias
      ansible.builtin.file:
        src: "{{ repo_dir }}/config/nvim/files/{{ item.name }}"
        path: "{{ home }}/.config/{{ item.name }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0700"
        state: "link"
      loop:
        - { name: "lazyvim" }
        - { name: "nvim" }

    # - name: nvim - Install npm packages
    #   block:
        # - name: nvim - Install `tsserver` language server packages
        #   # https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver
        #   # Must be installed globally for `styled-components` to work
        #   block:
        #     - name: nvim - Install "typescript" package
        #       become: true
        #       community.general.npm:
        #         name: "typescript"
        #         global: true
        #     - name: nvim - Install "typescript-language-server" package
        #       become: true
        #       community.general.npm:
        #         name: "typescript-language-server"
        #         global: true

        # - name: nvim - Install packages to support styled-components
        #   # https://github.com/pmizio/typescript-tools.nvim?tab=readme-ov-file#-styled-components-support
        #   block:
        #     - name: nvim - Install "@styled/typescript-styled-plugin" package
        #       become: true
        #       community.general.npm:
        #         name: "@styled/typescript-styled-plugin"
        #         global: true
        #     - name: nvim - Install "styled/typescript-styled-plugin" package
        #       become: true
        #       community.general.npm:
        #         name: "typescript-styled-plugin"
        #         global: true

        # - name: nvim - Install new-component (joshwcomeau)
        #   # https://www.joshwcomeau.com/react/file-structure/#more-boilerplate-11
        #   # I added a zsh alias so that I can call this component with `nc`
        #   become: true
        #   community.general.npm:
        #     name: "new-component"
        #     global: true

        # - name: nvim - Install ngrok
        #   # you must run a command to add the user token to a config file, check the documentation (the account was created with Github credentials)
       #   become: true
        #   community.general.npm:
        #     name: "ngrok"
        #     global: true
