- tags: hypr,dunst
  block:

    - name: Hypr_tofi - Install package from AUR
      # tofi      # Tiny rofi / dmenu replacement for wlroots-based Wayland compositors
      ansible.builtin.shell: 'paru -S --skipreview tofi'


    - name: Create config files
      block:
      - name: Hypr_tofi - Create directories
        ansible.builtin.file:
          path: "{{ home }}/.config/tofi"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: 0700
          state: directory

      - name: Hypr_tofi - Process templates
        tags: theme
        ansible.builtin.template:
          src: "files/{{ item.name }}"
          dest: "{{ home }}/.config/tofi/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: 0600
        loop:
          - { name: "config" }

