# --- dotfiles

- tags: alacritty_mabq
  block:

  - name: workstation | users | mabq | dotfiles | alacritty
    ansible.builtin.template:
      src: users/mabq/alacritty/alacritty.yml
      dest: /home/mabq/.config/alacritty/
      owner: mabq
      group: mabq
      mode: '0600'

