- tags: flameshot
  block:

    - name: Install packages
      block:
      - name: Install package from AUR (the one from the extra repo doest work)
        tags: aur
        block:
          - name: flameshot - Check if flameshot is already installed
            ansible.builtin.command: "which flameshot"
            register: which_flameshot
            ignore_errors: true

          - name: flameshot - Install flameshot
            when: which_flameshot.rc != 0
            # Powerful yet simple to use screenshot software
            ansible.builtin.shell: 'paru -S --skipreview flameshot-git'

      - name: flameshot - Install grim
        #`flameshot` won't work without this package
        become: true
        community.general.pacman:
          state: latest
          name:
            - grim    # Screenshot utility for Wayland

    - name: flameshot - Link the whole directory
      # link the whole directory, there is nothing sensible here
      ansible.builtin.file:
        src: "{{ repo_dir }}/config/flameshot/files"
        path: "{{ home }}/.config/flameshot"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0700"
        state: "link"

