- tags: swappy
  block:

    - name: swappy - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - swappy      # A Wayland native snapshot editing tool
          - grim        # Screenshot utility for Wayland
          - slurp       # Select a region in a Wayland compositor


    - name: Create config files
      block:
      - name: swappy - Create directories
        ansible.builtin.file:
          path: "{{ home }}/{{ item.path }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '700'
          state: directory
        loop:
          - { path: ".config/swappy" }
          - { path: "screenshots" }

      - name: swappy - Create links
        ansible.builtin.file:
          src: "{{ repo_dir }}/tasks/config/swappy/files/{{ item.name }}"
          path: "{{ home }}/.config/swappy/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '600'
          state: "link"
        loop:
          - { name: "config" }

