- tags: ssh
  block:
    - name: ssh - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - openssh       # SSH protocol implementation for remote login, command execution and file transfer
          - expect        # A tool for automating interactive applications (used to add the private key passphrase, see below)


    - name: Client side configurations
      block:
        - name: ssh - Create directories
          ansible.builtin.file:
            path: "{{ home }}/.ssh"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: '700'
            state: directory

        - name: ssh - Copy ssh keys
          ansible.builtin.template:
            src: "files/{{ item.name }}"
            dest: "{{ home }}/.ssh/{{ item.name }}"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "{{ item.mode }}"
          with_items:
            - { name: "{{ ssh_key_name }}", mode: '600' }
            - { name: "{{ ssh_key_name }}.pub", mode: '644' }

        - name: ssh - Create links
          ansible.builtin.file:
            src: "{{ repo_dir }}/tasks/config/ssh/files/{{ item.name }}"
            path: "{{ home }}/.ssh/{{ item.name }}"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: '600'
            state: "link"
          loop:
            - { name: "config" }

        - name: ssh - Add public key to authorized keys
          # This might seem like a ssh server configuration but it is not,
          # it is tightly related to each user.
          # Access any machine from any other machine (single pair of keys).
          ansible.posix.authorized_key:
            user: "{{ user }}"
            # must pass the content of the key, not the key path.
            key: "{{ lookup('file', '{{ home }}/.ssh/{{ ssh_key_name }}.pub') }}"


    - name: Server side configurations
      block:
        - name: ssh - Start and enable ssh daemon
          become: true
          ansible.builtin.systemd_service:
            name: "sshd.service"
            state: "started"
            enabled: true

        - name: ssh - Disable password authentication for the root user by default
          become: true
          ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: "^#PermitRootLogin"
            line: "PermitRootLogin prohibit-password" 

        - name: ssh - Disable password authentication for all users (if instructed)
          ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: "^#PasswordAuthentication"
            line: "PasswordAuthentication no" 
          when: ssh_disable_password_authentication


    - name: Add private key passphrase to ssh-agent
      # Required to clone private repositories later in this playbook, add the 
      # tags of all tags that clone a private repository
      tags: fontconfig
      block:
        - name: ssh - Start and enable ssh-agent (as a user service) with systemd
          # https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user
          # Requires `SSH_AUTH_LOCK` environment variable (see zsh config)
          environment:
            # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#parameter-scope
            XDG_RUNTIME_DIR: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}"
          # User services do not require super user privileges.
          ansible.builtin.systemd_service:
            name: "ssh-agent.service"
            state: "started"
            enabled: true
            scope: "user"

        - name: ssh - Add passphrase for the private key
          # `ssh-add` does not accept the passphrase as an argument, the command
          # is meant to be used interactively. We need the help of `expect` to 
          # do it programmatically.
          ansible.builtin.shell: "expect -c 'spawn ssh-add {{ home }}/.ssh/{{ ssh_key_name }}; expect \"Enter passphrase for {{ home }}/.ssh/{{ ssh_key_name }}:\"; send \"{{ ssh_key_passphrase }}\r\"; interact'"


