- tags: noconfig
  block:
    - name: no-config - Install packages from Archlinux official repositories
      become: true
      community.general.pacman:
        state: latest
        name:
          # ------------------------------------------------------------------------
          #
          # Better core utils:
          - eza # Modern replacement for ls, community fork of exa (`ls` alternative)
          - fd # Simple, fast and user-friendly alternative to find (`find` alternative)
          - fzf # Command-line fuzzy finder (theme is setup in zsh 'exports' file)
          - skim # Fuzzy Finder in Rust!
          - ripgrep # A search tool that combines the usability of ag with the raw speed of grep (`grep` alternative)
          - ripgrep-all # rga: ripgrep, but also search in PDFs, E-Books, Office documents, zip, tar.gz, etc.
          - rsync # A fast and versatile file copying tool for remote and local files (`cp` alternative)
          - trash-cli # Command line trashcan (recycle bin) interface (`rm` alternative)
          - zoxide # A smarter cd command for your terminal (`cd` alternative)
          #
          # ------------------------------------------------------------------------
          #
          # Ansible:
          - ansible # Official assortment of Ansible collections
          - sshpass # Fool ssh into accepting an interactive password non-interactively (required by Ansible to run playbooks on remote managed nodes, in case you ever use this computer to run the `arch-base` playbook on another computer)
          #
          # ------------------------------------------------------------------------
          #
          # Help utilities:
          - man-db # A utility for reading man pages
          - man-pages # Linux man pages
          - tldr # Command line client for tldr, a collection of simplified and community-driven man pages
          #
          # ------------------------------------------------------------------------
          #
          # System monitor utilities:
          # - lm_sensors          # Collection of user space tools for general SMBus access and hardware monitoring
          # - lsof                # Lists open files for running Unix processes
          - bottom # A graphical process/system monitor (`htop` alternative)
          - hwinfo # Hardware detection tool from openSUSE
          - inxi # Full featured CLI system information tool
          - fastfetch # Like Neofetch, but much faster because written in C
          #
          # ------------------------------------------------------------------------
          #
          # Filesystem utilities:
          - dosfstools # DOS filesystem utilities
          - exfat-utils # Utilities for exFAT file system (required to format external disks)
          - mtools # A collection of utilities to access MS-DOS disks
          #
          # ------------------------------------------------------------------------
          #
          # Compression/Uncompression utilities (used by zsh custom function `extract`):
          - p7zip # Command-line file archiver with high compression ratio
          - unarchiver # unar and lsar: Objective-C tools for uncompressing archive files
          - unrar # The RAR uncompression program
          - unzip # For extracting and viewing files in .zip archives
          - zip # Compressor/archiver for creating and modifying zipfiles
          #
          # ------------------------------------------------------------------------
          #
          # Network utilities:
          # - bind-tools          # A complete, highly portable implementation of the DNS protocol
          # - nfs-utils           # Support programs for Network File Systems
          # - whois               # Intelligent WHOIS client
          - bandwhich # Terminal bandwidth utilization tool
          - ethtool # Utility for controlling network drivers and hardware
          - traceroute # Tracks the route taken by packets over an IP network
          - wavemon # Ncurses-based monitoring application for wireless network devices
          - wget # Network utility to retrieve files from the Web (used by Neovim to download files on the internet when pressing `gf`)
          - speedtest-cli # Command line interface for testing internet bandwidth using speedtest.net
          - aria2 # Download utility that supports HTTP(S), FTP, BitTorrent, and Metalink
          #
          # ------------------------------------------------------------------------
          #
          # Firewalls and ports:
          # - opensnitch          # A GNU/Linux application firewall
          # - ufw                 # Uncomplicated and easy to use CLI tool for managing a netfilter firewall
          - nmap # Utility for network discovery and security auditing (great to check open ports)
          #
          # ------------------------------------------------------------------------
          #
          # Audio:
          # Read https://wiki.archlinux.org/title/PipeWire
          - pipewire-alsa # Low-latency audio/video router and processor - ALSA configuration
          - pipewire-jack # Low-latency audio/video router and processor - JACK replacement
          - pipewire-pulse # Replaces `pulseaudio` and `pulseaudio-bluetooth`
          - pavucontrol # PulseAudio Volume Control (replaced with helvum, issues when changing headphones profile)
          # `wireplumber` is installed as a dependency of all pipewire packages.
          # The `pactl` command is provided by PulseAudio client library package `libpulse`, which is installed with `pipewire-pulse` as a dependency.
          #
          # ------------------------------------------------------------------------
          #
          # Images:
          - nsxiv # Neo (or New or Not) Simple (or Small or Suckless) X Image Viewer
          #
          # ------------------------------------------------------------------------
          #
          # Browsers:
          # - chromium # A web browser built for speed, simplicity, and security
          - firefox # Standalone web browser from mozilla.org (the flatpak version solves the whatsapp problem but cannot work with keepassxc)
          #
          # ------------------------------------------------------------------------
          #
          # Torrents:
          - qbittorrent # An advanced BitTorrent client programmed in C++, based on Qt toolkit and libtorrent-rasterbar
          #
          # ------------------------------------------------------------------------
          #
          # Books:
          - evince # Document viewer (PDF, PostScript, XPS, djvu, dvi, tiff, cbr, cbz, cb7, cbt)
          - mdbook # Create book from markdown files, like Gitbook but implemented in Rust
          # - foliate # A simple and modern GTK eBook reader
          #
          # ------------------------------------------------------------------------
          #
          # Office:
          - inkscape # Professional vector graphics editor
          # - kicad # Electronic schematic and printed circuit board (PCB) design tools
          # - kicad-library # KiCad symbol, footprint and template libraries
          # - libreoffice-fresh # (installed with flatpak)
          #
          # ------------------------------------------------------------------------
          #
          # Scanning:
          - hplip # Drivers for HP DeskJet, OfficeJet, Photosmart, Business Inkjet and some LaserJet
          # - xsane # A GTK-based X11 frontend for SANE and plugin for Gimp (no longer in the pacman repository)
          #
          # ------------------------------------------------------------------------
          #
          # Other utils:
          - figlet # A program for making large letters out of ordinary text
          - pastel # A command-line tool to generate, analyze, convert and manipulate colors
          - translate-shell # A command-line interface and interactive shell for Google Translate
          # - stow                # Manage installation of multiple software in the same directory tree
          #
          # ------------------------------------------------------------------------
          #
          # Programming:
          - hyperfine # A command-line benchmarking tool
          - jq # Command-line JSON processor
          - python-xmljson # Converts XML into JSON/Python dicts/arrays and vice-versa.
          # - tgpt # AI Chatbots in terminal without needing API keys
          # - parallel # A shell tool for executing jobs in parallel
          # - go
          # - shellcheck
          #
          # ------------------------------------------------------------------------
          #
          # Clipboard manager:
          - copyq # Clipboard manager with searchable and editable history
          #
          # ------------------------------------------------------------------------

    - name: no-config - Install packages from flathub
      community.general.flatpak:
        name:
          # Verified developers only!, for non-verified applications use paru.
          # - org.mozilla.firefox
          - tv.plex.PlexDesktop
          - org.libreoffice.LibreOffice
          # - com.brave.Browser
          - org.localsend.localsend_app
          # - app.zen_browser.zen (browsers installed through flatpak cannot communicate with keepassxc)
          - org.keepassxc.KeePassXC

    - name: no-config - Install packages from AUR
      # Once installed, AUR packages won't be reinstalled, update them manually with `paru`
      tags: aur
      block:
        - name: Zen browser
          block:
            - name: no-config - Check if Zen browser is already installed
              ansible.builtin.shell: "which zen-browser"
              register: which_zen
              ignore_errors: true
            - name: no-config - Install zen-browser-bin
              when: which_zen != 0
              ansible.builtin.shell: "paru -S --skipreview zen-browser-bin"

        - name: Plex media server
          # (start the service manually when required to avoid consumming resources)
          block:
            - name: no-config - Check if Plex Media Server is already installed
              ansible.builtin.shell: "pacman -Q | rg plex-media-server"
              register: which_plex
              ignore_errors: true
            - name: no-config - Install plex-media-server
              when: which_plex.rc != 0
              # The back-end media server component of Plex (server sources must be configured manually)
              ansible.builtin.shell: "paru -S --skipreview plex-media-server"

        - name: Zoom
          block:
            - name: no-config - Check if Zoom is already installed
              ansible.builtin.command: "which zoom"
              register: which_zoom
              ignore_errors: true
            - name: no-config - Install Zoom
              when: which_zoom.rc != 0
              # Video Conferencing and Web Conferencing Service
              ansible.builtin.shell: "paru -S --skipreview zoom"

        - name: Kalker
          block:
            - name: no-config - Check if Kalker is already installed
              ansible.builtin.command: "which kalker"
              register: which_kalker
              ignore_errors: true
            - name: no-config - Install Kalker
              when: which_kalker.rc != 0
              # A calculator program that supports user-defined variables, functions, derivation, and integration.
              ansible.builtin.shell: "paru -S --skipreview kalker-bin"
