- tags: bluetooth
  block:

    - name: bluetooth - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - bluez           # Daemons for the bluetooth protocol stack
          - bluez-utils     # Development and debugging utilities for the bluetooth protocol stack


    - name: bluetooth - Link the whole directory
      # link the whole directory, there is nothing sensible here
      ansible.builtin.file:
        src: "{{ repo_dir }}/config/bluetooth/files"
        path: "{{ home }}/.config/bluetooth"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0700"
        state: "link"

