#!/usr/bin/env bash

# -- https://github.com/tmux/tmux/wiki/Getting-Started#list-of-style-and-format-options

# -- this file contains bar-layout configurations that do not include colors

set -g status-justify "absolute-centre" # center window labels

set -g status-right "" # remove clock and hostname info

set -g status-left " #{session_name}  "
set -g status-left-length "100"

set -g window-status-separator " "
set -g window-status-format " #{window_name} "
set -g window-status-current-format " #{window_name} "
set -g automatic-rename on # let programs automatically rename a tab
