# --- Bindings -----------------------------------------------------------------

#     Search for the "KEY BINDINGS" section in the tmux man page for all info.
#     List all key bindings with `{prefix}-?`.

# Easier reload
bind-key R run-shell "tmux source-file $HOME/.config/tmux/tmux.conf; tmux display-message 'Tmux configuration reloaded'"

# tmux-sessioniner (use uppercase letters)
# bind-key -r B run-shell "$HOME/.config/tmux/scripts/tmux-sessionizer.sh ~/projects/arch-base/"
# bind-key -r S run-shell "$HOME/.config/tmux/scripts/tmux-sessionizer.sh ~/projects/arch-setup/"
# bind-key -r L run-shell "$HOME/.config/tmux/scripts/tmux-sessionizer.sh ~/projects/learning/"
# # (temp projects)
# bind-key -r G run-shell "$HOME/.config/tmux/scripts/tmux-sessionizer.sh ~/projects/local/"

# Last session (same concept of `cd -`)
# bind-key -r - switch-client -l

# Easier window swap (left/right) - deprecated, use `<prefix>S-,` instead
# bind-key -r P "swap-window -s -1; previous-window"
# bind-key -r N "swap-window -s +1; next-window"

# --- Vim-tmux-navigator -------------------------------------------------------

# Ctrl keys are used by harpoon

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h'  'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j'  'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k'  'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l'  'select-pane -R'

bind-key -T copy-mode-vi 'M-h' select-pane -L
bind-key -T copy-mode-vi 'M-j' select-pane -D
bind-key -T copy-mode-vi 'M-k' select-pane -U
bind-key -T copy-mode-vi 'M-l' select-pane -R
