# --- Sensible keybindings -----------------------------------------------------

#     See https://github.com/tmux-plugins/tmux-sensible

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on


# --- General ------------------------------------------------------------------

# Use space as the prefix key
unbind-key C-b
set -g prefix C-space
bind-key C-space send-prefix

# Fix Colors and italics for most terminal emulators
#   https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable mouse support
set -g mouse on

# Increase pane display time (default 750)
set -g display-panes-time 3000

# Start windows and panes at 1 (default 0) (not possible to start sessions at 1)
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Vim-like copy mode
set -g mode-keys "vi"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Use the current working directory for new windows
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# Yazi
#   Enable image preview to work correctly in tmux (https://github.com/sxyazi/yazi/wiki/Image-preview-within-tmux)
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

