- name: Setup mabq
  tags: mabq
  block:

  # ---------------------------------------------------------------------------
  
  - name: Import variables - mabq
    tags: always
    include_vars: users/mabq.yml

  # ---------------------------------------------------------------------------

  - name: Config user - {{ username }}
    tags: mabq_config
    block:

    - name: Create group - {{ username }}
      ansible.builtin.group:
        name: "{{ username }}"

    - name: Create user - {{ username }}
      block:

      - name: Generate password hash - {{ username }}
        # `/etc/shadow` stores the password hash, never the password itself
        ansible.builtin.command: "openssl passwd -6 {{ password }}"
        register: password_hash

      - name: Create user - {{ username }}
        ansible.builtin.user:
          name: "{{ username }}"
          group: "{{ username }}"
          # - adm: commonly used to give read access to protected logs. It has full read access to journal files
          # - wheel: commonly used to give privileges to perform administrative actions
          groups: adm,wheel
          # see `/etc/shadow`
          password: "{{ password_hash.stdout }}"
          shell: /bin/bash

    - name: Setup privilege elevation - {{ username }}
      #  https://wiki.archlinux.org/title/List_of_applications/Security#Privilege_elevation
      ansible.builtin.copy:
        src: users/{{ username }}/sudo/sudoers
        dest: /etc/sudoers.d/{{ username }}
        owner: root
        group: root
        mode: 0440

  # ---------------------------------------------------------------------------
  
    # This are the user's configuration files only, ssh is installed and configured in the "system-setup" section
    
  - name: SSH config - {{ username }}
    tags: mabq_ssh
    block:

    - name: Ensure directories for SSH - {{ username }}
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0700

    - name: Install private ssh key - {{ username }}
      ansible.builtin.copy:
        src: "users/{{ username }}/ssh/id_ed25519"
        dest: "/home/{{ username }}/.ssh/id_ed25519"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0600

    - name: Install public ssh key - {{ username }}
      ansible.builtin.copy:
        src: "users/{{ username }}/ssh/id_ed25519.pub"
        dest: "/home/{{ username }}/.ssh/id_ed25519.pub"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644

    - name: Add the public key to the `authorized_key` file
      # one key to rule them all
      ansible.posix.authorized_key:
        user: "{{ username }}"
        key: "{{ item }}"
      with_file:
        - "users/{{ username }}/ssh/id_ed25519.pub"

    # Note: becasue I use a single key there is no need to create a config file. The default value of `AddKeysToAgent` is `yes`.

  # ---------------------------------------------------------------------------
  
  - name: Git config - {{ username }}
    tags: mabq_git
    block:

    - name: Setup `.gitcongif` - {{ username }}
      ansible.builtin.copy:
        src: "users/{{ username }}/git/gitconfig"
        dest: "/home/{{ username }}/.gitconfig"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0600

  # ---------------------------------------------------------------------------
  
  - name: Tmux config - {{ username }}
    tags: mabq_tmux
    block:
  
    - name: Ensure directories for tmux - {{ username }}
      ansible.builtin.file:
        path: /home/{{ username }}/{{ item.dir }}
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0700
      with_items:
        - { dir: '.config' }
        - { dir: '.config/tmux' }
        - { dir: '.local' }
        - { dir: '.local/bin' }

    - name: Copy tmux config files - {{ username }}
      ansible.builtin.copy:
        src: users/{{ username }}/tmux/{{ item.src }}
        dest: /home/{{ username }}/{{ item.dest }}
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "{{ item.mode | default('0600') }}"
      with_items:
        - { src: 'scripts/tmux-sessionizer', dest: '.local/bin/tmux-sessionizer', mode: '0700' }

    - name: Template tmux config files - {{ username }}
      ansible.builtin.template:
        src: users/{{ username }}/tmux/{{ item.src }}
        dest: /home/{{ username }}/{{ item.dest }}
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "{{ item.mode | default('0600') }}"
      with_items:
        - { src: 'templates/tmux.conf', dest: '.config/tmux/tmux.conf' }

  # ---------------------------------------------------------------------------

    # - name: Dotfiles - git - {{ username }}
    #   copy:
    #     src: users/{{ username }}/{{ item.src }}
    #     dest: /home/{{ username }}/{{ item.dest }}
    #     owner: "{{ username }}"
    #     group: "{{ username }}"
    #     mode: 0600
    #   with_items:
    #     - { src: 'zsh/zshrc', dest: '.zshrc' }


