- name: base | users | mabq | include variables
  # the user password is stored in an encrypted variable
  tags: always
  include_vars: users/mabq.yml


# --- create user account

- tags: mabq_create
  block:

  - name: base | users | mabq | create group
    ansible.builtin.group:
      name: mabq

  - name: base | users | mabq | generate password hash
    # cannot use the `passwd` command via Ansible, therefore we must manually hash
    # the password, the `-6` flag corresponds to the sha512 algorithm.
    # for more info visit:
    #   - https://wiki.archlinux.org/title/SHA_password_hashes
    #   - https://www.slashroot.in/how-are-passwords-stored-linux-understanding-hashing-shadow-utils
    #   - https://www.baeldung.com/linux/shadow-passwords#3-crypt-and-encryption-algorithms
    ansible.builtin.command: "openssl passwd -6 {{ password }}"
    register: password_hash

  - name: base | users | mabq | create user
    ansible.builtin.user:
      name: mabq
      # primary group
      group: mabq
      # supplementary groups --- https://wiki.archlinux.org/title/Users_and_groups#Group_list
      groups: adm,wheel
      # `/etc/shadow` stores passwords hashes (sha512)
      password: "{{ password_hash.stdout }}"
      # in order to be able to log in, the login shell must be one of those listed in `/etc/shells`
      shell: /bin/bash

  - name: base | users | mabq | create sudoers file
    ansible.builtin.copy:
      src: users/mabq/sudoers/mabq
      # https://wiki.archlinux.org/title/Sudo#Configure_sudo_using_drop-in_files_in_/etc/sudoers.d
      dest: /etc/sudoers.d/
      owner: root
      group: root
      mode: 0440


# --- dotfiles

- tags: mabq_dotfiles
  block:

  - name: base | users | mabq | template dotfiles
    # use the template module to share a single location for all src files
    ansible.builtin.template:
      src: "users/mabq/{{ item.src }}"
      dest: "/home/mabq/{{ item.dest }}"
      owner: mabq
      group: mabq
      mode: "{{ item.mode | default('0600') }}"
    with_items:
      # use directories as `dest`, the same `src` filename will be used
      - { src: 'git/.gitconfig', dest: '.', mode: '0644' }
      - { src: 'ssh/id_ed25519', dest: '.ssh/' }
      - { src: 'ssh/id_ed25519.pub', dest: '.ssh/', mode: '0640' }
      - { src: 'tmux/tmux.conf', dest: '.config/tmux/' }
      - { src: 'tmux/tmux-sessionizer.sh', dest: '.config/tmux/scripts/', mode: '0700' }
      # - { src: 'zsh/.zshenv',                 dest: '.zshenv' }
      # - { src: 'zsh/.zshrc',                  dest: '.config/zsh/.zshrc' }
      # - { src: 'zsh/bindkey.zsh',             dest: '.config/zsh/bindkey.zsh' }
      # - { src: 'zsh/functions.zsh',           dest: '.config/zsh/functions.zsh' }
      # - { src: 'zsh/options.zsh',             dest: '.config/zsh/options.zsh' }
      # - { src: 'zsh/plugins.zsh',             dest: '.config/zsh/plugins.zsh' }
      # - { src: 'joshuto/joshuto.toml',        dest: '.config/joshuto/joshuto.toml' }
      # - { src: 'joshuto/keymap.toml',         dest: '.config/joshuto/keymap.toml' }
      # - { src: 'joshuto/mimetype.toml',       dest: '.config/joshuto/mimetype.toml' }
      # - { src: 'joshuto/theme.toml',          dest: '.config/joshuto/theme.toml' }
      # - { src: 'joshuto/icons.toml',          dest: '.config/joshuto/icons.toml' }
      # - { src: 'joshuto/preview_file.sh',     dest: '.config/joshuto/preview_file.sh',       mode: '0700'}

  - name: base | users | mabq | ssh authorized_keys
    # since we use a single pair of ssh keys for all services this step authorizes each machine to access every other machine and vise-versa
    ansible.posix.authorized_key:
      user: mabq
      key: "{{ lookup('file', '/home/mabq/.ssh/id_ed25519.pub') }}"


