- name: base | users | mabq | include variables
  # the user password is stored in a variable encrypted
  tags: always
  include_vars: users/mabq.yml


# --- create user account

- name: base | users | mabq | create group
  tags: groups,mabq,users
  ansible.builtin.group:
    name: mabq
    state: present

  # The `user` module below requires the hashed version of the password (sha512)
  # The `-6` flag corresponds to the sha512 algorithm
- name: base | users | mabq | generate password hash
  tags: users,mabq,sudo
  ansible.builtin.command: "openssl passwd -6 {{ password }}"
  register: password_hash

  # Groups:
  #   adm - commonly used to give read access to protected logs, it has full read access to journal files
  #   wheel - commonly used to give privileges to perform administrative actions
  # The file `/etc/shadow` stores the password hash (sha512), never the password itself
- name: base | users | mabq | create user
  tags: users,mabq,sudo
  ansible.builtin.user:
    name: mabq
    group: mabq # primary group
    groups: adm,wheel # supplementary groups
    state: present
    comment: "Alejandro Banderas"
    password: "{{ password_hash.stdout }}"
    shell: /bin/bash

  #  See https://wiki.archlinux.org/title/List_of_applications/Security#Privilege_elevation
- name: base | users | mabq | add sudoers file
  tags: users,mabq,sudo
  ansible.builtin.copy:
    src: users/mabq/sudo/sudoers
    dest: /etc/sudoers.d/mabq
    owner: root
    group: root
    mode: 0440

# --- 

- name: "mabq - create config directories"
  tags: users,mabq,dotfiles
  file:
    path: /home/mabq/{{ item.dir }}
    state: directory
    owner: "mabq"
    group: "mabq"
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/joshuto' }
    - { dir: '.config/tmux' }
    - { dir: '.config/zsh' }
    - { dir: '.cache' }
    - { dir: '.cache/zsh' }    # for zsh history
    - { dir: '.local' }
    - { dir: '.local/bin' }
    - { dir: '.ssh' }
      # neovim

# ---

- name: "mabq - add ssh public key to `~/.ssh/authorized_keys`"
  # by using a single key, this step authorizes each machine to access all other machines
  tags: users,mabq,dotfiles
  ansible.posix.authorized_key:
    user: "mabq"
    key: "{{ item }}"
  with_file:
    - "users/mabq/ssh/id_ed25519.pub"


- name: "mabq - copy dotfiles"
  tags: users,mabq,dotfiles
  ansible.builtin.copy:
    src: "users/mabq/{{ item.src }}"
    dest: "/home/mabq/{{ item.dest }}"
    owner: "mabq"
    group: "mabq"
    mode: "{{ item.mode | default('0600') }}"
  with_items:
    # ssh
    - { src: 'ssh/id_ed25519',              dest: '.ssh/id_ed25519' }
    - { src: 'ssh/id_ed25519.pub',          dest: '.ssh/id_ed25519.pub',              mode: '0640' }
    # git
    - { src: 'git/gitconfig',               dest: '.gitconfig' }
    # joshuto
    - { src: 'joshuto/joshuto.toml',        dest: '.config/joshuto/joshuto.toml' }
    - { src: 'joshuto/keymap.toml',         dest: '.config/joshuto/keymap.toml' }
    - { src: 'joshuto/mimetype.toml',       dest: '.config/joshuto/mimetype.toml' }
    - { src: 'joshuto/theme.toml',          dest: '.config/joshuto/theme.toml' }
    - { src: 'joshuto/icons.toml',          dest: '.config/joshuto/icons.toml' }
    - { src: 'joshuto/preview_file.sh',     dest: '.config/joshuto/preview_file.sh',       mode: '0700'}
    # tmux
    - { src: 'tmux/tmux-sessionizer',       dest: '.local/bin/tmux-sessionizer',      mode: '0700' }
    # zsh
    - { src: 'zsh/.zshenv',                 dest: '.zshenv' }
    - { src: 'zsh/.zshrc',                  dest: '.config/zsh/.zshrc' }
    - { src: 'zsh/bindkey.zsh',             dest: '.config/zsh/bindkey.zsh' }
    - { src: 'zsh/functions.zsh',           dest: '.config/zsh/functions.zsh' }
    - { src: 'zsh/options.zsh',             dest: '.config/zsh/options.zsh' }
    - { src: 'zsh/plugins.zsh',             dest: '.config/zsh/plugins.zsh' }


- name: "mabq - process templates"
  tags: users,mabq,dotfiles
  ansible.builtin.template:
    src: "users/mabq/{{ item.src }}"
    dest: "/home/mabq/{{ item.dest }}"
    owner: "mabq"
    group: "mabq"
    mode: "{{ item.mode | default('0600') }}"
  with_items:
    # tmux
    - { src: 'tmux/tmux.conf', dest: '.config/tmux/tmux.conf' }
    # zsh
    - { src: 'zsh/aliases.zsh', dest: '.config/zsh/aliases.zsh' }
    - { src: 'zsh/exports.zsh', dest: '.config/zsh/exports.zsh' }

# ---

# zsh 
#   ssh-agent as a wrapper is not working, do it with systemd

