# ------------------------------------------------------------------------------

# Source files
source=~/.config/hypr/source/colors.conf
source=~/.config/hypr/source/variables.conf
source=~/.config/hypr/source/monitors.conf
source=~/.config/hypr/source/binds.conf

# ------------------------------------------------------------------------------

# Master
# https://wiki.hyprland.org/Configuring/Master-Layout

master {
    #special_scale_factor = 0.8
    new_is_master = false
    #new_on_top = false
    no_gaps_when_only = true
    #orientation = left
    #inherit_fullscreen = true
}

# Dwindle
# https://wiki.hyprland.org/Configuring/Dwindle-Layout/

dwindle {
    #pseudotile = false
    #col.group_border = 0x66777700
    #col.group_border_active = 66ffff00
    #force_split = 2 # 0-2
    #preserve_split = true
    #special_scale_factor = 0.8
    #split_width_multiplier = 1.0
    no_gaps_when_only = true
    #use_active_for_splits = true
}

# ------------------------------------------------------------------------------

# Executing
# https://wiki.hyprland.org/Configuring/Keywords/#executing

exec = hyprpaper   # set the wallpaper

# sets all monitors’ DPMS status. Do not use with a keybind directly
# exec = dpms on

exec-once = playerctld daemon   # enable media keys
exec-once = dunst
exec-once = kmonad ~/.config/kmonad/mxkeys.kbd
exec-once = sudo logid -c ~/.config/logid/logid.cfg
exec-once = dropbox
exec-once = keepassxc

# ------------------------------------------------------------------------------
