- tags: hypr,waybar
  block:

    - name: hypr_waybar - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - waybar      # Highly customizable Wayland bar for Sway and Wlroots based compositors


    - name: Create config files
      block:
      - name: hypr_waybar - Create directories
        ansible.builtin.file:
          path: "{{ home }}/.config/waybar"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: 0700
          state: directory

      - name: hypr_waybar - Create links
        ansible.builtin.file:
          src: "{{ repo_dir }}/tasks/config/hypr_waybar/files/{{ item.name }}"
          path: "{{ home }}/.config/waybar/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: 0600
          state: "link"
        loop:
          - { name: "config" }

      - name: hypr_waybar - Process templates
        tags: theme
        ansible.builtin.template:
          src: "files/{{ item.name }}"
          dest: "{{ home }}/.config/waybar/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: 0600
        loop:
          - { name: "styles.css" }

