- name: git - create config file from template
  tags: dotfiles,git
  ansible.builtin.template:
    src: "git/.gitconfig"
    dest: "{{ home }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

