- name: SSH client config files
  tags: dotfiles,ssh
  block:
  - name: ssh - Ensure `.ssh` directory exists
    ansible.builtin.file:
      path: "{{ home }}/.ssh"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700
      state: directory
  - name: ssh - Install ssh keys and client config file
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: 'ssh/id_ed25519', dest: "{{ home }}/.ssh", mode: '0600' }
      - { src: 'ssh/id_ed25519.pub', dest: "{{ home }}/.ssh", mode: '0644' }
      - { src: 'ssh/config', dest: "{{ home }}/.ssh", mode: '0600' }

- name: SSH server config files
  tags: dotfiles,ssh
  block:
  - name: ssh - Add public key to authorized_keys
    # since we use a single pair of ssh keys any machine will be able to access any other machine
    ansible.posix.authorized_key:
      user: "{{ user }}"
      key: "{{ lookup('file', '{{ home }}/.ssh/id_ed25519.pub') }}"
  - name: ssh - Disable password authentication for all users
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '{{ item.regex }}'
      line: '{{ item.line }}'
    loop:
      - { regex: "^#PermitRootLogin", line: "PermitRootLogin prohibit-password" }
      - { regex: "^#PasswordAuthentication", line: "PasswordAuthentication no" }

- name: ssh - Install openssh
  tags: install,ssh
  ansible.builtin.package:
    name: openssh
    state: latest

- name: ssh - Systemd configurations
  tags: install,ssh
  block:
  - name: ssh - Enable and start the sshd 'system' service
    ansible.builtin.systemd_service:
      name: "sshd.service"
      enabled: true
      state: "started"
      scope: "system"
  - name: ssh - Enable and start the ssh-agent as a 'user' service
    block:
    - name: ssh - Enable and start the ssh-agent as a 'user' service
      ansible.builtin.systemd_service:
        name: "ssh-agent.service"
        enabled: true
        state: "user"
    - name: ssh - Add a required config file for the ssh-agent user service
      # https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user
      block:
      - name: ssh - Ensure `~/.config/environment.d` directory exists
        ansible.builtin.file:
          path: "{{ home }}/.config/environment.d"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: 0700
          state: directory
      - name: ssh - Copy `ssh-agent.conf` to `~/.config/environment.d/`
        # see notes in the file
        ansible.builtin.copy:
          src: "ssh/ssh-agent.conf"
          dest: "{{ home }}/.config/environment.d/"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: "0744"

