
# Do not skip packages, partial updates are unsupported (https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported)

- name: base | system_setup | pacman | enable Color
  tags: system_setup,pacman
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#(Color)'
    line: '\1'

- name: base | system_setup | pacman | enable VerbosePkgLists
  tags: system_setup,pacman
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#(VerbosePkgLists)'
    line: '\1'

- name: base | system_setup | pacman | enable ParallelDownloads
  tags: system_setup,pacman
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#(ParallelDownloads)'
    line: '\1 = 5'
