- tags: hypr,waybar
  block:

    - name: hypr_waybar - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - waybar      # Highly customizable Wayland bar for Sway and Wlroots based compositors

    - name: Create config files
      block:
      - name: hypr_waybar - Create directories
        ansible.builtin.file:
          path: "{{ home }}/.config/waybar/scripts"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '700'
          state: directory

      - name: hypr_waybar - Create links
        # The `toggle` script is always called via shortcut, no need to create 
        # a link.
        ansible.builtin.file:
          src: "{{ repo_dir }}config/hypr_waybar/{{ item.src }}"
          path: "{{ home }}/.config/waybar/{{ item.path }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: "{{ item.mode }}"
          state: "link"
        loop:
          - { src: "files/config", path: "config", mode: "600" }
          - { src: "files/style.css", path: "style.css", mode: "600" }
          - { src: "scripts/toggle.sh", path: "scripts/toggle.sh", mode: "700" }
          # link the whole themes directory, that way you can add or remove themes without having to change this playbook
          - { src: "files/themes", path: "themes", mode: "700" }

      # - name: hypr_waybar - Process templates
      #   tags: theme
      #   ansible.builtin.template:
      #     src: "files/{{ item.name }}"
      #     dest: "{{ home }}/.config/waybar/{{ item.name }}"
      #     owner: "{{ user }}"
      #     group: "{{ user }}"
      #     mode: '600'
      #   loop:
      #     - { name: "style.css" }

