#!/bin/sh

#
# AUTHOR: theprimeagen --- this is a modified version of https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer
# DATE: Feb 10, 2023
# MODIFIED: Aug 07, 2023
#
# DESCRIPTION
#   Simplify the creation of tmux sessions. Both, zsh and neovim, have mappings pointing to this script (Ctrl-f)
#
# REQUIRED PACKAGES
#   fd, fzf
#

# Add any directoried you want (just use `$HOME` instead of `~`)
directories="$HOME/ $HOME/projects/ $HOME/projects/ansible"

if [[ $# -eq 1 ]]; then
    # you can pass the directory directly, see `~/.config/tmux/tmux.conf`
    working_directory=$1
else
    working_directory=$(fd --unrestricted --exact-depth=1 --type=directory . $directories | fzf)
fi

if [[ -z $working_directory ]]; then
    exit 0
fi

# Use the directory name as the session name (session names cannot include dots, replace them with `_`)
session_name=$(basename "$working_directory" | tr . _)

# Create the session (if necessary) in detached mode
if ! tmux has-session -t $session_name 2> /dev/null; then
    tmux new-session -s $session_name -c $working_directory -d
fi 

# Go to the selected session (if we reach this point it means that tmux is running)
if [[ -n $TMUX ]]; then 
    # the current terminal is already attached to tmux, just switch (if necessary)
    tmux switch-client -t $session_name
else
    # attach to tmux session
    tmux attach-session -t $session_name
fi

