- name: base | user | openssh | ensure `.ssh` directory exists
  tags: dotfiles,ssh
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    state: directory

- name: base | user | openssh | copy ssh keys
  tags: dotfiles,ssh
  # public key is not encrypted but it makes sense to put both keys in the same source dir
  ansible.builtin.copy:
    src: "openssh/{{ item.src }}"
    dest: "{{ home }}/.ssh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'id_ed25519', mode: '0600' }
    - { src: 'id_ed25519.pub', mode: '0644' }

- name: base | user | openssh | link client config file
  tags: dotfiles,ssh
  ansible.builtin.file:
    src: "{{ srcdir }}/roles/base/links/openssh/config"
    path: "{{ home }}/.ssh/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
    state: "link"

- name: base | user | openssh | add public key to authorized_keys
  # this might seem like a ssh server configuration but it is not, it is tightly related to each user
  tags: dotfiles,ssh
  # access any machine from any other machine (single pair of keys)
  ansible.posix.authorized_key:
    user: "{{ user }}"
    # must pass the content of the key, not the key path
    key: "{{ lookup('file', '{{ home }}/.ssh/id_ed25519.pub') }}"
