- tags: logiops
  block:

    - name: logiops - Install package from AUR
      tags: aur
      block:
        - name: logiops - Check if logiops is already installed
          ansible.builtin.command: "which logid"
          register: which_logid
          ignore_errors: true

        - name: logiops - Install logiops
          when: which_logid.rc != 0
          # An unofficial driver for Logitech HID++>2.0 mice and keyboard
          ansible.builtin.shell: 'paru -S --skipreview logiops'


    - name: Create config files
      block:
      - name: logiops - Create directories
        ansible.builtin.file:
          path: "{{ home }}/.config/logiops"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '700'
          state: directory

      - name: logiops - Create links
        ansible.builtin.file:
          src: "{{ repo_dir }}/tasks/config/logiops/files/{{ item.name }}"
          path: "{{ home }}/.config/logiops/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '600'
          state: "link"
        loop:
          - { name: "logid.cfg" }


    - name: Avoid running logid with sudo
      # https://github.com/PixlOne/logiops/issues/32#issuecomment-715887184
      block:
        - name: logiops - Ensure the `hidraw` group exists
          become: true
          ansible.builtin.group:
            name: hidraw
            state: present
 
        - name: logiops - Add your user to the `hidraw` group
          become: true
          ansible.builtin.user:
            append: true
            groups: hidraw
            name: "{{ user }}"

        - name: logiops - Create udev rule
          become: true
          ansible.builtin.copy:
            # Assigns the hidraw devices to group hidraw, and gives that group RW access:
            content: 'KERNEL=="hidraw[0-9]*", GROUP="hidraw", MODE="0660"'
            dest: /etc/udev/rules.d/46-logiops-hidraw.rules
          register: rule

        - name: logiops - Ensure the `hidraw` drivers are loaded
          become: true
          ansible.builtin.command: modprobe hidraw
          when: rule.changed

