# ------------------------------------------------------------------------------
#             
#               _____                    _       _         _
#              |_   _|__ _ __ ___  _ __ | | __ _| |_ ___  | |
#                | |/ _ \ '_ ` _ \| '_ \| |/ _` | __/ _ \ | |
#                | |  __/ | | | | | |_) | | (_| | ||  __/ |_|
#                |_|\___|_| |_| |_| .__/|_|\__,_|\__\___| (_)
#                                 |_|
#             
# ------------------------------------------------------------------------------

$color_black_low = rgb({{ color_black_low | remove_hash_from_hex_color }})
$color_black = rgb({{ color_black | remove_hash_from_hex_color }})
$color_black_high = rgb({{ color_black_high | remove_hash_from_hex_color }})

$color_red_low = rgb({{ color_red | remove_hash_from_hex_color }})
$color_red = rgb({{ color_red | remove_hash_from_hex_color }})
$color_red_high = rgb({{ color_red | remove_hash_from_hex_color }})

$color_green_low = rgb({{ color_green | remove_hash_from_hex_color }})
$color_green = rgb({{ color_green | remove_hash_from_hex_color }})
$color_green_high = rgb({{ color_green | remove_hash_from_hex_color }})

$color_yellow_low = rgb({{ color_yellow | remove_hash_from_hex_color }})
$color_yellow = rgb({{ color_yellow | remove_hash_from_hex_color }})
$color_yellow_high = rgb({{ color_yellow | remove_hash_from_hex_color }})

$color_blue_low = rgb({{ color_blue | remove_hash_from_hex_color }})
$color_blue = rgb({{ color_blue | remove_hash_from_hex_color }})
$color_blue_high = rgb({{ color_blue | remove_hash_from_hex_color }})

$color_magenta_low = rgb({{ color_magenta | remove_hash_from_hex_color }})
$color_magenta = rgb({{ color_magenta | remove_hash_from_hex_color }})
$color_magenta_high = rgb({{ color_magenta | remove_hash_from_hex_color }})

$color_cyan_low = rgb({{ color_cyan | remove_hash_from_hex_color }})
$color_cyan = rgb({{ color_cyan | remove_hash_from_hex_color }})
$color_cyan_high = rgb({{ color_cyan | remove_hash_from_hex_color }})

$color_white_low = rgb({{ color_white_low | remove_hash_from_hex_color }})
$color_white = rgb({{ color_white | remove_hash_from_hex_color }})
$color_white_high = rgb({{ color_white_high | remove_hash_from_hex_color }})

$color_highlight_low = rgb({{ color_highlight_low | remove_hash_from_hex_color }})
$color_highlight = rgb({{ color_highlight | remove_hash_from_hex_color }})
$color_highlight_high = rgb({{ color_highlight_high | remove_hash_from_hex_color }})

