- name: base | first | ensure directories | `~/.config`
  tags: always
  ansible.builtin.file:
    path: "{{ home }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    state: directory
