- name: base | software | kmonad | install
  tags: software,kmonad
  community.general.pacman:
    state: latest
    executable: "paru"
    name: kmonad-bin  # An advanced keyboard manager - static binary version

# - name: base | software | zsh | ensure `~/.config/zsh` directory exists
#   tags: software,zsh
#   ansible.builtin.file:
#     path: "{{ home }}/.config/zsh"
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: 0700
#     state: directory
#
# - name: base | software | zsh | link config files
#   tags: software,zsh
#   ansible.builtin.file:
#     src: "{{ srcdir }}/roles/base/links/zsh/{{ item.src }}"
#     path: "{{ item.dest }}"
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: 0600
#     state: "link"
#   loop:
#     - { src: ".zshenv", dest: "{{ home }}/.zshenv" }
#     - { src: ".zshrc", dest: "{{ home }}/.config/zsh/.zshrc" }
#     - { src: "options.zsh", dest: "{{ home }}/.config/zsh/options.zsh" }
#     - { src: "bindkey.zsh", dest: "{{ home }}/.config/zsh/bindkey.zsh" }
#     - { src: "functions.zsh", dest: "{{ home }}/.config/zsh/functions.zsh" }
#     - { src: "exports.zsh", dest: "{{ home }}/.config/zsh/exports.zsh" }
#     - { src: "aliases.zsh", dest: "{{ home }}/.config/zsh/aliases.zsh" }
#     - { src: "plugins.zsh", dest: "{{ home }}/.config/zsh/plugins.zsh" }

# - name: base | software | zsh | generate `colors-tty.sh` file
#   tags: software,zsh,theme
#   ansible.builtin.template:
#     src: "zsh/colors-tty.sh"
#     dest: "{{ home }}/.config/zsh/"
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: 0700

