# Notes:
#
#   Advantanges of QMK or ZMK:
#     - Ergonomics --- splitted, ortholineas, increased pinlu column stagger
#     - This would not be necessary, the configurations live on the keyboard
#     - More options. Probably better performance. No CPU consumption.
#
#   Advantages of Kmonad:
#     - Any keyboard, event the builtin keyboard on laptops


# --- install packages

- name: base | software | kmonad | check if kmonad is already installed
  tags: software,kmonad
  ansible.builtin.command: "kmonad --version"
  register: kmonad_version
  ignore_errors: true

# Note: Once installed this will never run again, update manually with paru
- name: install kmonad (if not already installed)
  tags: software,kmonad
  when: kmonad_version.rc != 0
  # paru must be executed as non-root
  become: false
  # the `ansible.builtin.git` module is not working with paru
  ansible.builtin.shell: 'paru -S --skipreview kmonad-bin'  # An advanced keyboard manager - static binary version

- name: base | software | kmonad | install evtest
  # https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-know-which-event-file-corresponds-to-my-keyboard
  tags: software,kmonad
  ansible.builtin.package:
    state: latest
    name: evtest  # Input device event monitor and query tool


# --- get uinput permissions for user
#     https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions

- name: base | software | kmonad | make sure the "uinput" group exists
  tags: software,kmonad
  ansible.builtin.group:
    name: uinput

- name: base | software | kmonad | add user to the "input" and "uinput" groups
  tags: software,kmonad
  ansible.builtin.user:
    name: "{{ user }}"
    groups: input,uinput
    append: true

- name: base | software | kmonad | create udev rule with right permissions (if necessary)
  tags: software,kmonad
  ansible.builtin.copy:
    dest: "/etc/udev/rules.d/99-kmonad.rules"
    content: KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
    mode: 0644
  register: dev_rule

- name: base | software | kmonad | reload udev rules if necessary
  tags: software,kmonad
  ansible.builtin.shell: 'udevadm control --reload-rules && udevadm trigger'
  when: dev_rule.changed


# --- load the `uinput` kernel module
#     https://github.com/kmonad/kmonad/blob/cec7d4ac3644c96737da23124e473e13ace5156c/keymap/tutorial.kbd#L111

- name: base | software | kmonad | check loaded kernel modules
  tags: software,kmonad
  ansible.builtin.command: 'lsmod'
  register: loaded_modules

- name: base | software | kmonad | load "uinput" drivers (if necessary)
  tags: software,kmonad
  ansible.builtin.command: 'modprobe uinput'
  when: "'uinput' not in loaded_modules.stdout_lines"


# --- link config files

- name: base | software | kmonad | link config files
  tags: software,kmonad
  ansible.builtin.file:
    src: "{{ srcdir }}/roles/base/links/kmonad/{{ item.src }}"
    path: "{{ home }}/.config/kmonad/{{ item.path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
    state: "link"
  with_items:
    - { src: 'mxkeys.kbd', path: 'mxkeys.kbd' }
    # - { src: 'magic-keyboard.kbd', path: 'magic-keyboard.kbd' }

