- name: workstation | system_setup | microcode | install for Intel
  tags: system_setup,microcode
  ansible.builtin.package:
    name: intel-ucode
    state: latest
  when: is_intel

- name: workstation | system_setup | microcode | install for AMD
  tags: system_setup,microcode
  ansible.builtin.package:
    name: amd-ucode
    state: latest
  when: not is_intel
