# --- install packages

- name: base | software | nvim | install neovim
  tags: software,nvim
  ansible.builtin.package:
    state: latest
    name: 
      - neovim  # Fork of Vim aiming to improve user experience, plugins, and GUIs

# --- link config files

- name: base | software | nvim | ensure directories
  tags: software,nvim
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory
  with_items:
    - { path: '{{ home }}/.config/nvim/lua/mabq' }
    - { path: '{{ home }}/.config/nvim/after/plugin' }
    - { path: '{{ home }}/.config/nvim/spell' }

- name: base | software | nvim | link config files
  tags: software,nvim
  ansible.builtin.file:
    src: "{{ srcdir }}/roles/base/links/nvim/{{ item.src }}"
    path: "{{ home }}/.config/nvim/{{ item.path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
    state: "link"
  with_items:
    # main
    - { src: 'init.lua', path: 'init.lua' }
    # lua
    - { src: 'lua/mabq/init.lua', path: 'lua/mabq/init.lua' }
    - { src: 'lua/mabq/lazy.lua', path: 'lua/mabq/lazy.lua' }
    - { src: 'lua/mabq/remap.lua', path: 'lua/mabq/remap.lua' }
    - { src: 'lua/mabq/set.lua', path: 'lua/mabq/set.lua' }
    # plugins
    - { src: 'after/plugin/comment.lua', path: 'after/plugin/comment.lua' }
    - { src: 'after/plugin/harpoon.lua', path: 'after/plugin/harpoon.lua' }
    - { src: 'after/plugin/highlight-yank.lua', path: 'after/plugin/highlight-yank.lua' }
    - { src: 'after/plugin/lsp.lua', path: 'after/plugin/lsp.lua' }
    - { src: 'after/plugin/rose-pine.lua', path: 'after/plugin/rose-pine.lua' }
    - { src: 'after/plugin/telescope.lua', path: 'after/plugin/telescope.lua' }
    - { src: 'after/plugin/treesitter.lua', path: 'after/plugin/treesitter.lua' }
    - { src: 'after/plugin/undotree.lua', path: 'after/plugin/undotree.lua' }
    # spell
    - { src: 'spell/en.utf-8.add', path: 'spell/en.utf-8.add' }

