- name: base | software | pacman | change lines in pacman configuration file
  tags: install,pacman
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: '{{ item.regex }}'
    line: '{{ item.line }}'
  loop:
    - { regex: "^#Color", line: "Color" }
    - { regex: "^#VerbosePkgLists", line: "VerbosePkgLists" }
    - { regex: "^#ParallelDownloads", line: "ParallelDownloads = 5" }
    # - { regex: "^#IgnorePkg", line: "IgnorePkg   = ansible linux linux-headers linux-lts linux-lts-headers" }

