- name: base | software | pacman | change pacman config file
  tags: software,pacman
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: '{{ item.regex }}'
    line: '{{ item.line }}'
  loop:
    - { regex: "^#Color", line: "Color" }
    - { regex: "^#VerbosePkgLists", line: "VerbosePkgLists" }
    - { regex: "^#ParallelDownloads", line: "ParallelDownloads = 10" }
    # - { regex: "^#IgnorePkg", line: "IgnorePkg   = ansible linux linux-headers linux-lts linux-lts-headers" }

- name: base | software | paru | check if paru is already installed
  tags: software,pacman
  ansible.builtin.command: "paru --version"
  register: paru_version
  ignore_errors: true

# Note: Once installed this will never run again, update paru with paru itself
- name: install paru (if not already installed)
  tags: software,pacman
  when: paru_version.rc != 0
  block:
  - name: base | software | paru | clone the repo
    # the repo must be cloned as the non-root user to set the correct file permissions for `makepkg` (below) to run successfully
    become_user: "{{ user }}"
    ansible.builtin.git:
      repo: https://aur.archlinux.org/paru.git
      dest: "/tmp/paru/"
  - name: base | software | paru | build paru
    # makepkg cannot be run as root
    become: false
    # `-s` installs dependencies automatilly
    # `-i` install the package after successfully building it
    # `--noconfirm` answers "yes" to all prompts without asking questions
    ansible.builtin.shell: "cd /tmp/paru && makepkg -si --noconfirm"


