- name: base | software | paru | clone the repo
  tags: software,paru
  ansible.builtin.git:
    repo: https://aur.archlinux.org/paru.git
    dest: "{{ home }}/.paru/"
  register: paru_clone

- name: base | software | paru | notification
  tags: software,paru
  ansible.builtin.debug:
    msg: "about to build paru (if necessary), this step could take a couple of minutes"

- name: base | software | paru | build paru
  tags: software,paru
  # makepkg must not be run as root
  become: false
  ansible.builtin.shell: "cd {{ home }}/.paru && makepkg -si"
  # the `before` and `after` values are hashes of the current commit and the latest commit after the git task, respectively
  when: paru_clone.before != paru_clone.after

