- name: base | software | paru | check if paru is already installed
  tags: software,paru
  ansible.builtin.command: "paru --version"
  register: paru_version
  ignore_errors: true

# Note: Once installed this will never run again, update paru with paru itself
- name: install paru (if not previously installed)
  tags: software,paru
  when: paru_version.rc != 0
  block:
  - name: base | software | paru | clone the repo
    ansible.builtin.git:
      repo: https://aur.archlinux.org/paru.git
      # use the tmp directory to automatically delete the repo on next boot and have all required permissions
      dest: "/tmp/paru/"
  - name: base | software | paru | letting you know
    ansible.builtin.debug:
      msg: "About to build paru, this will take several minutes"
  - name: base | software | paru | build paru
    ansible.builtin.shell: "cd /tmp/paru && makepkg -si"
    # makepkg cannot be run as root
    become: false

