# --- install packages
#     https://yazi-rs.github.io/docs/installation

- name: base | software | yazi | install yazi
  tags: software,yazi
  ansible.builtin.package:
    state: latest
    name: 
      - yazi                # Blazing fast terminal file manager written in Rust, based on async I/O
      - ffmpegthumbnailer   # Lightweight video thumbnailer that can be used by file managers
      # - unarchiver          # unar and lsar: Objective-C tools for uncompressing archive files
      - jq                  # Command-line JSON processor
      - poppler             # PDF rendering library based on xpdf 3.0
      - fd                  # Simple, fast and user-friendly alternative to find
      - ripgrep             # A search tool that combines the usability of ag with the raw speed of grep
      - fzf                 # Command-line fuzzy finder
      - zoxide              # A smarter cd command for your terminal

# --- config files

- name: base | software | yazi | ensure `~/.config/yazi` directory
  tags: software,yazi
  ansible.builtin.file:
    path: "{{ home }}/.config/yazi"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory

- name: base | software | yazi | link config files
  tags: software,yazi
  ansible.builtin.file:
    src: "{{ srcdir }}/roles/base/links/yazi/{{ item.src }}"
    path: "{{ home }}/.config/yazi/{{ item.path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
    state: "link"
  with_items:
    - { src: 'yazi.toml', path: 'yazi.toml' }
    - { src: 'disable-status-line.lua', path: 'disable-status-line.lua' }

- name: base | software | yazi | template theme
  tags: software,yazi
  ansible.builtin.template:
    src: "yazi/theme.toml"
    dest: "{{ home }}/.config/yazi/theme.toml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

