- name: base | software | zsh | install
  tags: software,zsh
  ansible.builtin.package:
    state: latest
    name:
      - zsh  # A very advanced and programmable command interpreter (shell) for UNIX
      - starship  # The cross-shell prompt for astronauts
      - zsh-autosuggestions  # Fish-like autosuggestions for zsh
      - zsh-history-substring-search  # ZSH port of Fish history search (up arrow)
      - zsh-syntax-highlighting  # Fish shell like syntax highlighting for Zsh

- name: base | software | zsh | change default shell
  tags: software,zsh
  ansible.builtin.shell:
    cmd: "chsh -s $(which zsh) {{ user }}"

- name: base | software | zsh | create shared history file
  tags: software,zsh
  block:
  - name: base | software | zsh | ensure `~/.cache/zsh` directory
    ansible.builtin.file:
      path: "{{ home }}/.cache/zsh"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
      state: directory
  - name: base | software | zsh | create history file
    ansible.builtin.file:
      path: "{{ home }}/.cache/zsh/history"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0600
      state: touch

- name: base | software | zsh | ensure `~/.config/zsh` directory exists
  tags: software,zsh
  ansible.builtin.file:
    path: "{{ home }}/.config/zsh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    state: directory

- name: base | software | zsh | link config files
  tags: software,zsh
  ansible.builtin.file:
    src: "{{ srcdir }}/roles/base/links/zsh/{{ item.src }}"
    path: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
    state: "link"
  loop:
    - { src: ".zshenv", dest: "{{ home }}/.zshenv" }
    - { src: ".zshrc", dest: "{{ home }}/.config/zsh/.zshrc" }
    - { src: "options.zsh", dest: "{{ home }}/.config/zsh/options.zsh" }
    - { src: "bindkey.zsh", dest: "{{ home }}/.config/zsh/bindkey.zsh" }
    - { src: "functions.zsh", dest: "{{ home }}/.config/zsh/functions.zsh" }
    - { src: "exports.zsh", dest: "{{ home }}/.config/zsh/exports.zsh" }
    - { src: "aliases.zsh", dest: "{{ home }}/.config/zsh/aliases.zsh" }
    - { src: "plugins.zsh", dest: "{{ home }}/.config/zsh/plugins.zsh" }

- name: base | software | zsh | generate `colors-tty.sh` file
  tags: software,zsh,theme
  ansible.builtin.template:
    src: "zsh/colors-tty.sh"
    dest: "{{ home }}/.config/zsh/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

