- tags: flatpak
  block:
    - name: flatpak - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - flatpak # Linux application sandboxing and distribution framework


  # Used to install spotify while `spotify-launcher` fixes an issue
