- tags: nodejs
  block:

    # Use `n` to interactively manage your nodejs versions (https://github.com/tj/n)
    # I use the `n-install` script to install and update `n` (https://github.com/mklement0/n-install)

    - name: nodejs - Check if `n` is already installed
      ansible.builtin.stat: "{{ home }}/n"
      register: ndir
      ignore_errors: true

    - name: nodejs - Install `n` (if not already installed)
      when: ndir.stat.isdir == false
      # `-s` is for silent
      # everything after `--` are arguments passed to the script
      # `-y` assumes yes as the reply to all prompts (run unattended)
      # `-n` suppresses updating of the relevant shell initialization file
      ansible.builtin.shell: 'curl -L https://bit.ly/n-install | bash -s -- -y -n'

