# vim:fileencoding=utf-8:foldmethod=marker

# : Manager 

[manager]
cwd = { fg = "#ebbcba" }

# Hovered
hovered = { fg = "#e0def4", bg = "#403d52" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#191724", bg = "#ebbcba", italic = true }
find_position = { fg = "#908caa", italic = true }

# Marker
marker_selected = { fg = "#1f1d2e", bg = "#c4a7e7" }
marker_copied   = { fg = "#1f1d2e", bg = "#9ccfd8" }
marker_cut      = { fg = "#1f1d2e", bg = "#ebbcba" }

# Tab
tab_active   = { fg = "#e0def4", bg = "#191724", bold = true }
tab_inactive = { fg = "#6e6a86", bg = "#191724" }
tab_width    = 2

# Border
border_symbol = "│"
border_style  = { fg = "#21202e" }

# Highlighting
#syntect_theme = "~/.config/bat/themes/Catppuccin-mocha.tmTheme"

# : 


# : Status 

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#45475a", bg = "#45475a" }

# Mode
mode_normal = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
mode_select = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
mode_unset  = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#45475a" }
progress_error  = { fg = "#f38ba8", bg = "#45475a" }

# Permissions
permissions_t = { fg = "#89b4fa" }
permissions_r = { fg = "#f9e2af" }
permissions_w = { fg = "#f38ba8" }
permissions_x = { fg = "#a6e3a1" }
permissions_s = { fg = "#7f849c" }

# : 


# : Input 

[input]
border   = { fg = "#89b4fa" }
title    = {}
value    = {}
selected = { reversed = true }

# : 


# : Select 

[select]
border   = { fg = "#89b4fa" }
active   = { fg = "#f5c2e7" }
inactive = {}

# : 


# : Tasks 

[tasks]
border  = { fg = "#89b4fa" }
title   = {}
hovered = { underline = true }

# : 


# : Which 

[which]
mask            = { bg = "#313244" }
cand            = { fg = "#94e2d5" }
rest            = { fg = "#9399b2" }
desc            = { fg = "#f5c2e7" }
separator       = "  "
separator_style = { fg = "#585b70" }

# : 


# : Help 

[help]
on      = { fg = "#f5c2e7" }
exec    = { fg = "#94e2d5" }
desc    = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }
footer  = { fg = "#45475a", bg = "#cdd6f4" }

# : 


# : File-specific styles 

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#94e2d5" },

	# Videos
	{ mime = "video/*", fg = "#f9e2af" },
	{ mime = "audio/*", fg = "#f9e2af" },

	# Archives
	{ mime = "application/zip",             fg = "#f5c2e7" },
	{ mime = "application/gzip",            fg = "#f5c2e7" },
	{ mime = "application/x-tar",           fg = "#f5c2e7" },
	{ mime = "application/x-bzip",          fg = "#f5c2e7" },
	{ mime = "application/x-bzip2",         fg = "#f5c2e7" },
	{ mime = "application/x-7z-compressed", fg = "#f5c2e7" },
	{ mime = "application/x-rar",           fg = "#f5c2e7" },

	# Fallback
	{ name = "*", fg = "#e0def4" },
	{ name = "*/", fg = "#908caa" }
]

# : 

