# --- Workspace rules
#     https://wiki.hyprland.org/Configuring/Workspace-Rules/

# --- Normal workspaces
workspace = 1, on-created-empty:alacritty

# --- Special workspaces
#     Used for utilities without poluting normal workspaces.
#     The `--class` parameter changes the class name of the terminal
#     window so that window rules can be applied.
#     Gaps help you understand that you are currently on a special workspace.
workspace = special:terminals, on-created-empty:alacritty, gapsout:50

workspace = special:calculator, on-created-empty:alacritty --class Kalker --command kalker

workspace = special:explorer, on-created-empty:alacritty --class Yazi --command yazi, gapsout:50

workspace = special:video, on-created-empty:alacritty --class Yazi --command yazi ~/Alejandro/media, gapsout:50

workspace = special:music, on-created-empty:spotify-launcher, gapsout:50

workspace = special:passwords, on-created-empty:keepassxc, gapsout:50

