- import_tasks: first/change_remote_url.yml
- import_tasks: first/ensure_directories.yml

- import_tasks: software/pacman.yml
- import_tasks: software/openssh.yml
- import_tasks: software/git.yml
- import_tasks: software/microcode.yml
# - import_tasks: software/zsh.yml
# - import_tasks: software/tmux.yml
# - import_tasks: software/neovim.yml
# - import_tasks: software/no_config.yml

- import_tasks: system_setup/clock.yml
- import_tasks: system_setup/locales.yml
- import_tasks: system_setup/logging.yml
