- block:

  # create users and setup config files
  - import_tasks: users/mabq.yml

  # setup the ansible environment (to review)
  - import_tasks: software/install.yml

  # install base packages
  
  # perform remaining tasks

