- name: base | system | openssh | start and enable `sshd.service`
  ansible.builtin.systemd_service:
    name: "sshd.service"
    enabled: true
    state: "started"

- name: base | system | openssh | enable and start `ssh-agent.service` as a 'user' service
  # https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user
  # requires `SSH_AUTH_LOCK` environment variable (see zsh config)
  ansible.builtin.systemd_service:
    name: "ssh-agent.service"
    enabled: true
    state: "started"
    scope: "user"
  # become must be false to activate a user service
  become: false
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#parameter-scope
  # must be executed via `ansible-pull`, environment variables are evaluated on the controller
  environment:
    XDG_RUNTIME_DIR: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}"

- name: base | system | openssh | disable password authentication for root
  tags: dotfiles,ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin"
    line: "PermitRootLogin prohibit-password" 

- name: base | system | openssh | disable password authentication for all users
  tags: dotfiles,ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication"
    line: "PasswordAuthentication no" 
  when: "{{ ssh_disable_password_authentication_for_all_users }}"
