- tags: yazi
  block:
    - name: yazi - Install packages
      block:
        - name: yazi - Install packages from official repositories
          become: true
          community.general.pacman:
            state: latest
            name:
              - yazi # Blazing fast terminal file manager written in Rust, based on async I/O
              - ffmpegthumbnailer # (optional, for video thumbnails) Lightweight video thumbnailer that can be used by file managers
              - p7zip # (optional, for archive extraction and preview) Command-line file archiver with high compression ratio
              - unarchiver # (optional, for archive preview) unar and lsar: Objective-C tools for uncompressing archive files
              - jq # (optional, for JSON preview) Command-line JSON processor
              - poppler # (optional, for PDF preview) PDF rendering library based on xpdf 3.0
              - fd # (optional, for file searching) Simple, fast and user-friendly alternative to find
              - ripgrep # (optional, for file content searching) A search tool that combines the usability of ag with the raw speed of grep
              - fzf # (optional, for quick file subtree navigation) Command-line fuzzy finder
              - zoxide # (optional, for historical directories navigation) A smarter cd command for your terminal
              - imagemagick # (for SVG, Font, HEIC, and JPEG XL preview) An image viewing/manipulation program
              - nemo # Cinnamon file manager (Nautilus fork)

    - name: yazi - Link the whole directory
      # link the whole directory, there is nothing sensible here
      ansible.builtin.file:
        src: "{{ repo_dir }}/config/yazi/files"
        path: "{{ home }}/.config/yazi"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0700"
        state: "link"

    - name: yazi - Create symlinks for external disks
      block:
        - name: yazi - Create mount directory for disks
          become: true
          ansible.builtin.file:
            path: "/mnt"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "777" # all users should be able to read/write/execute on external disks
            state: directory
        - name: yazi - Link /mnt to ~/Disks
          # link the whole mnt directory to access disks from the home directory
          become: true
          ansible.builtin.file:
            src: "/mnt"
            path: "{{ home }}/Disks"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "0700"
            state: "link"
