- tags: git 
  block:

    - name: git - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - git             # The fast distributed version control system
          - git-delta       # Syntax-highlighting pager for git and diff output

    - name: git - Process templates
      ansible.builtin.template:
        src: "files/{{ item.name }}"
        dest: "{{ home }}/{{ item.name }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '600'
      loop:
        - { name: ".gitconfig" }


