

# For more info see:
#   - `man tmux`
#   - https://github.com/tmux/tmux/wiki/Getting-Started

# Inspiration:
#   - https://github.com/LearnLinuxTV/personal_ansible_desktop_configs/blob/main/roles/base/files/users/jay/tmux/tmux.conf.workstation
#   - https://github.com/ThePrimeagen/.dotfiles/blob/master/tmux/.tmux.conf


# keybindings ------------------------------------------------------------------

# take me there quickly (uppercase letters only)

bind -r W run-shell "~/.local/bin/tmux-sessionizer ~/projects/ansible/ansible-archlinux-workstation/"
bind -r L run-shell "~/.local/bin/tmux-sessionizer ~/projects/learning/"
bind -r D run-shell "~/.local/bin/tmux-sessionizer ~/dotfiles"

# easier reload
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# change the prefix key
set -g prefix C-space
unbind C-b
bind C-space send-prefix

# vim-like selection and copy
bind -T copy-mode-vi "v" send-keys -X begin-selection
bind -T copy-mode-vi "y" send-keys -X copy-selection-and-cancel

# additional window navigation shortcuts
#   (use Alt because Ctrl is used for `rename-window` and `move-window`)
# bind -n M-"," select-window -p (try to use default p)
# bind -n M-"." select-window -n (try to use default n)

# easier pane selection
#   (pane navigation is being given priotity over `select last window` Ctrl-l)
#   (use default `;` to select last pane)
#   (use default `q` to select pane by number)
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# use current working directory for new panes and windows
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


# options ----------------------------------------------------------------------

set -g mouse on

set -g set-clipboard on

set -g escape-time 0
set -g repeat-time 350    # shorten time to be able to start typing sooner
set -g display-time 5000
set -g display-panes-time 10000

set -g history-limit 10000
set -g buffer-limit 10

set -ga terminal-overrides ",{{ terminal }}:Tc"    # correct colors
set -g default-terminal "tmux-256color"

set -g mode-keys "vi"    # for copy-mode
set -g status-keys "vi"    # for the command prompt

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on    # manually with `:movew -r`
set -g set-titles on
set -g set-titles-string "#T"    # correct terminal emulator window titles when using ssh
set -g automatic-rename on


# style and format ------------------------------------------------------------- 

#   (https://github.com/tmux/tmux/wiki/Getting-Started#list-of-style-and-format-options)

set -g pane-active-border-style "fg={{ sel_high }}"
set -g pane-border-style "fg={{ bg_low }}"

set -g message-style "bg={{ yellow }},fg={{ bg_medium }}"
set -g message-command-style "bg={{ yellow }},fg={{ bg_medium }}"

set -g mode-style "bg={{ yellow }},fg={{ bg_high }}"    # selection style

set -g display-panes-active-colour "{{ blue }}"    # active pane number color
set -g display-panes-colour "{{ red }}"    # inactive pane number color

set -g status-style "fg={{ fg_high }},bg={{ bg_medium }}"

set -g status-left "  #S "
set -g status-left-style "italics,fg={{ cyan }}"
set -g status-left-length 100    # automatically trucated if space is required

set -g status-justify "absolute-centre"
set -g window-status-style "fg={{ fg_low }}"
set -g window-status-current-style "fg={{ fg_high }}"
set -g window-status-separator "   "
# set -g window-status-format " #I:#W#{?window_flags,#{window_flags}, } "
# set -g window-status-current-format " #I:#W#{?window_flags,#{window_flags}, } "
set -g window-status-activity-style "fg={{ blue }}"

set -g status-right ""    # remove clock and hostname info

