# ------------------------------------------------------------------------------
#             
#               _____                    _       _         _
#              |_   _|__ _ __ ___  _ __ | | __ _| |_ ___  | |
#                | |/ _ \ '_ ` _ \| '_ \| |/ _` | __/ _ \ | |
#                | |  __/ | | | | | |_) | | (_| | ||  __/ |_|
#                |_|\___|_| |_| |_| .__/|_|\__,_|\__\___| (_)
#                                 |_|
#             
# ------------------------------------------------------------------------------
#
# Default config files available at:
#   https://github.com/sxyazi/yazi/tree/main/yazi-config/preset
#
# ------------------------------------------------------------------------------

[manager]

cwd = { fg = "{{ color_blue }}" }

# (reversed does not work as intended)
# hovered = { fg = "{{ color_white_high }}", bg = "{{ color_highlight_low }}" }
hovered = { fg = "{{ color_white_high }}", bg = "{{ color_highlight_low }}" }
preview_hovered = { bg = "{{ color_highlight_low }}", fg = "{{ color_white }}" }

find_keyword = { fg = "{{ color_cyan }}", italic = true }
find_position = { fg = "{{ color_cyan }}", italic = true }

marker_selected = { fg = "{{ color_magenta }}", bg = "{{ color_magenta }}" }
marker_copied = { fg = "{{ color_blue }}", bg = "{{ color_blue }}" }
marker_cut  = { fg = "{{ color_cyan }}", bg = "{{ color_cyan }}" }

tab_active = { fg = "{{ color_white_high }}", bg = "{{ color_black_low }}", bold = true }
tab_inactive = { fg = "{{ color_white_low }}", bg = "{{ color_black_low }}" }
tab_width = 2

border_symbol = "│"
border_style = { fg = "{{ color_highlight_low }}" }

folder_offset  = [ 0, 1, 0, 1 ]
preview_offset = [ 1, 2, 1, 2 ]

syntect_theme = ""

# ------------------------------------------------------------------------------


[select]

border   = { fg = "{{ color_cyan }}" }
active   = { fg = "{{ color_cyan }}" }
inactive = {}

# ------------------------------------------------------------------------------

[input]

border   = { fg = "{{ color_cyan }}" }
title    = {}
value    = { fg = "{{ color_white_high }}"}
selected = { reversed = true }

# ------------------------------------------------------------------------------

[completion]

border   = { fg = "{{ color_cyan }}" }
active   = { bg = "{{ color_white }}" }
inactive = {}

# ------------------------------------------------------------------------------

[tasks]

border  = { fg = "{{ color_cyan }}" }
title   = {}
hovered = { underline = true }

# ------------------------------------------------------------------------------

[which]

mask            = { bg = "{{ color_black }}" }
cand            = { fg = "{{ color_cyan }}" }
rest            = { fg = "{{ color_white_high }}" }
desc            = { fg = "{{ color_white_high }}" }
separator       = "  "
separator_style = { fg = "{{ color_white }}" }

# ------------------------------------------------------------------------------

[help]

on      = { fg = "{{ color_cyan }}" }
exec    = { fg = "{{ color_white_high }}" }
desc    = { fg = "{{ color_white_high }}" }
hovered = { bg = "{{ color_highlight_low }}" }
footer  = { fg = "{{ color_white_high }}", bg = "{{ color_black_low }}" }

# ------------------------------------------------------------------------------

[filetype]

rules = [
    # Since `reversed` color does not work, it makes no sense to assign colors
    # to file types.
    # Version 1.6 will allow custom colors for symbolic links (see https://github.com/sxyazi/yazi/issues/287#issuecomment-1769794925)
	{ name = "*/", fg = "{{ color_white_low }}" },
	{ name = "*", fg = "{{ color_white }}" },
]

# ------------------------------------------------------------------------------

[icons]

# Disable all custom icons, just folders and documents.
"*/" = " "
"*"  = " "

# ------------------------------------------------------------------------------

