# Default config files available at:
#   https://github.com/sxyazi/yazi/tree/main/yazi-config/preset


[manager]

cwd = { fg = "#a6e3a1" }

# (reversed does not work as intended)
# hovered = { fg = "{{ color_white_high }}", bg = "#313244" }
hovered = { fg = "#313244", bg = "#cdd6f4" }
preview_hovered = { bg = "#313244", fg = "#a6adc8" }

find_keyword = { fg = "#fab387", italic = true }
find_position = { fg = "#fab387", italic = true }

marker_selected = { fg = "#b4befe", bg = "#b4befe" }
marker_copied = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut  = { fg = "#f9e2af", bg = "#f9e2af" }

tab_active = { fg = "#89b4fa", bg = "#1e1e2e", bold = true }
tab_inactive = { fg = "#585b70", bg = "#1e1e2e" }
tab_width = 2

border_symbol = "│"
border_style = { fg = "#313244" }

folder_offset  = [ 0, 1, 0, 1 ]
preview_offset = [ 1, 2, 1, 2 ]

syntect_theme = ""

# ------------------------------------------------------------------------------


[select]

border   = { fg = "#fab387" }
active   = { fg = "#fab387" }
inactive = {}

# ------------------------------------------------------------------------------

[input]

border   = { fg = "#fab387" }
title    = {}
value    = { fg = "#cdd6f4"}
selected = { reversed = true }

# ------------------------------------------------------------------------------

[completion]

border   = { fg = "#fab387" }
active   = { bg = "#a6adc8" }
inactive = {}

# ------------------------------------------------------------------------------

[tasks]

border  = { fg = "#fab387" }
title   = {}
hovered = { underline = true }

# ------------------------------------------------------------------------------

[which]

mask            = { bg = "#181825" }
cand            = { fg = "#fab387" }
rest            = { fg = "#cdd6f4" }
desc            = { fg = "#cdd6f4" }
separator       = "  "
separator_style = { fg = "#a6adc8" }

# ------------------------------------------------------------------------------

[help]

on      = { fg = "#fab387" }
exec    = { fg = "#cdd6f4" }
desc    = { fg = "#cdd6f4" }
hovered = { bg = "#313244" }
footer  = { fg = "#cdd6f4", bg = "#1e1e2e" }

# ------------------------------------------------------------------------------

[filetype]

rules = [
    # Since `reversed` color does not work, it makes no sense to assign colors
    # to file types.
    # Version 1.6 will allow custom colors for symbolic links (see https://github.com/sxyazi/yazi/issues/287#issuecomment-1769794925)
	{ name = "*/", fg = "#7f849c" },
	{ name = "*", fg = "#a6adc8" },
]

# ------------------------------------------------------------------------------

[icons]

# Disable all custom icons, just folders and documents.
"*/" = " "
"*"  = " "

# ------------------------------------------------------------------------------

