# Default config:
#   https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
#
# Documentation:
#   https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
ratio = [ 1, 3, 3 ]
sort_by = "natural"
show_hidden = true

[tasks]
image_alloc = 0 # show images of any size
image_bound = [ 0, 0 ] # show images of any size

