-- -- disable netrw (recommended)
--
-- vim.g.loaded_netrw       = 1
-- vim.g.loaded_netrwPlugin = 1
--
-- --------------------------------------------------------------------------------
--
-- -- h, j, k, l style navigation and editing (https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#h-j-k-l-style-navigation-and-editing)
--
-- local api = require("nvim-tree.api")
--
-- -- local nvim_tree = require('nvim-tree')
--
-- -- if nvim_tree.is_window_open() then
-- --   -- The Nvim-tree window is opened
-- -- else
-- --   -- The Nvim-tree window is closed
-- -- end
--
-- local function custom_open()
--   local node = api.tree.get_node_under_cursor()
--   if node.nodes ~= nil then
--     -- expand or collapse folder
--     api.node.open.edit()
--   else
--     -- open file
--     api.node.open.edit()
--     -- close the tree if file was opened
--     api.tree.close()
--   end
-- end
--
-- local function custom_vsplit_preview()
--   local node = api.tree.get_node_under_cursor()
--   if node.nodes ~= nil then
--     -- expand or collapse folder
--     api.node.open.edit()
--   else
--     -- open file as vsplit
--     api.node.open.vertical()
--   end
--   -- refocus on tree if it was lost
--   api.tree.focus()
-- end
--
-- local function opts(desc)
--     return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
-- end
--
-- -- local function my_on_attach(bufnr)
--     -- default mappings
--     -- api.config.mappings.default_on_attach(bufnr)
--     -- custom mappings (only applicable when nvim-tree is attached)
--     -- vim.keymap.set("n", "l", custom_open, opts("Open and close tree"))
--     -- vim.keymap.set("n", "L", custom_vsplit_preview, opts("Open vsplit on current node"))
--     -- vim.keymap.set("n", "h", api.node.navigate.parent_close, opts("Parent close"))
--     -- vim.keymap.set("n", "H", api.tree.collapse_all, opts("Collapse All"))
-- -- end
--
-- -- -----------------------------------------------------------------------------
--
-- -- require("nvim-tree").setup({
-- --     sort = {},
-- --     view = {},
-- --     renderer = {},
-- --     filters = {},
-- --     on_attach = my_on_attach,
-- -- })
--
