- tags: tmux
  block:

    - name: tmux - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - tmux  # Terminal multiplexer


    - name: tmux - Create config files
      block:
      - name: tmux - Create directories
        ansible.builtin.file:
          path: "{{ home }}/.config/tmux/scripts"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '700'
          state: directory

      - name: tmux - Create links
        ansible.builtin.file:
          src: "{{ repo_dir }}/config/tmux/{{ item.name }}"
          path: "{{ home }}/.config/tmux/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: "{{ item.mode }}"
          state: "link"
        loop:
          - { src: "files/tmux.conf", path: "tmux.conf", mode: "0600" }
          - { src: "scripts/tmux-sessionizer.sh", path: "scripts/tmux-sessionizer.sh", mode: "0700" }

      - name: tmux - Process templates
        tags: theme
        ansible.builtin.template:
          src: "files/{{ item.name }}"
          dest: "{{ home }}/.config/tmux/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '600'
        loop:
          - { name: "theme.conf" }

