# Executing
#   https://wiki.hyprland.org/Configuring/Keywords/#executing

# Set wallpaper
exec-once = swaybg --mode fill --image ~/.local/share/wallpapers/elephant.png

# Must-have Hyprland software
# (dunst is managed as a systemd user service)
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# auto-launch
exec-once = sudo logid -c ~/.config/logiops/logid.cfg
exec-once = playerctld daemon &
exec-once = kmonad ~/.config/kmonad/mxkeys.kbd &
# (starting dropbox as a user service causes high cpu consumption issues, doing it manually here does not)
exec-once = dropbox &

