# Executing
#   https://wiki.hyprland.org/Configuring/Keywords/#executing

# wallpaper
exec-once = swaybg --mode fill --image ~/.local/share/wallpapers/elephant.png

# must-have Hyprland software
exec-once = dunst
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# auto-launch
exec-once = keepassxc
exec-once = sudo logid -c ~/.config/logid/logid.cfg
exec-once = playerctld daemon &
exec-once = kmonad ~/.config/kmonad/mxkeys.kbd &
exec-once = dropbox &

