# Executing
#   https://wiki.hyprland.org/Configuring/Keywords/#executing

# Set wallpaper
exec-once = swaybg --mode fill --image ~/.local/share/wallpapers/elephant.png

# Must-have Hyprland software
# (dunst is managed as a systemd user service)
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# auto-launch
# (keepassxc can be started with a keybind, no need to auto-launch)
# (dropbox is managed as a systemd user service)
exec-once = sudo logid -c ~/.config/logiops/logid.cfg
exec-once = playerctld daemon &
exec-once = kmonad ~/.config/kmonad/mxkeys.kbd &

