# Window rules & Special workspaces --------------------------------------------
#   https://wiki.hyprland.org/Configuring/Window-Rules/
#   use `hyprctl clients` to inspect window properties
#   these rules apply to all windows of the target class (see workspace-rules for workspace specific rules)

# Float all by default
windowrulev2 = float, class:(.)

# Brave
#   In some machines it starts with B and in others with b.
windowrulev2 = tile, class:((B|b)rave-browser)

# Alacritty
windowrulev2 = tile, class:(Alacritty)
windowrulev2 = opacity 0.97 override, class:(Alacritty)

# alacritty-music
windowrulev2 = center, class:(alacritty-music)
windowrulev2 = size 70% 80%, class:(alacritty-music)

# alacritty-calc
windowrulev2 = move 65% 5%, class:(alacritty-calc)
windowrulev2 = size 25% 25%, class:(alacritty-calc)

# alacritty-special
windowrulev2 = center, class:(alacritty-special)
windowrulev2 = size 50% 80%, class:(alacritty-special)

# KeePassXC
windowrulev2 = center, class:(org.keepassxc.KeePassXC)
windowrulev2 = size 70% 80%, class:(org.keepassxc.KeePassXC)
windowrulev2 = workspace special:secrets, class:(org.keepassxc.KeePassXC)

# ueberzugpp (images in terminal, avoid initial flickr)
# windowrulev2 = noanim, class:(ueberzugpp*)
# windowrulev2 = move -99999 -99999, class:(ueberzugpp*)

