# Start ssh-agent with systemd user:
#   https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user

# The user instance of systemd does not inherit any of the environment variables set in places like .bashrc etc. This variable will only apply for the user's user unit: `ssh-agent`
#   https://wiki.archlinux.org/title/Systemd/User#Environment_variables

# $XDG_RUNTIME_DIR is already available with a base archlinux installation

SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

