- name: base | system_setup | locales | add locales
  tags: system_setup,locales
  community.general.locale_gen:
    name: "{{ item }}.UTF-8"
    state: present
  loop: '{{ locales }}'
  register: locales

- name: base | system_setup | locales | set first locale in list as default locale
  tags: system_setup,locales
  ansible.builtin.command: "localectl set-locale LANG={{ locales[0] }}.UTF-8"
  when: locales.changed

